name: renovate-config-validator

on:
  push:
    paths:
      - '.github/renovate.json5'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-node@v3
      - run: npx --package renovate -c 'renovate-config-validator'
